### ISSUE TITLE
Example, docs ?

### ISSUE THREAD

**Issue by jon1012** [pfalcon/micropython-btreedb#1]
Hi,

The project sounds interesting and I am trying to make it work for my uses (esp32).
However, even if code is simple, reverse eng. isn't very fun :)

Do you have a little example or doc stub for this package ?

Thanks,
Jonathan

**Comment by Lisa999** [comment]
Done! See issues raised. I'm gonna use the improved btreedb in upyeasy... 

Cheers,

Lisa

**Comment by pfalcon** [comment]
Answering the original question: this project, as well as https://github.com/pfalcon/uorm, https://github.com/pfalcon/micropython-filedb are (see https://github.com/pfalcon/notes-pico/blob/master/requirements.txt) replaceable, simple object-relational managers for https://github.com/pfalcon/notes-pico , which is a pretty good an example to follow, and some docs to read too.

**Comment by pfalcon** [comment]
README has been added, giving the pointers.
