### ISSUE TITLE
Example use

### ISSUE THREAD

**Issue by Lisa999** [pfalcon/micropython-btreedb#3]
from . import db
from .db import EasyDB

db.db.connect()

db.EasyDB.create_table()

upy_id = db.EasyDB.create(test=1)
upy_id = db.EasyDB.create(test=2)
upy_id = db.EasyDB.create(test=3)

pkey='2017-09-26 00:04:34'
db.EasyDB.delete({"timestamp": pkey})

pkey='2017-09-26 00:06:54'
upy_id = db.EasyDB.get_id(pkey)

upy_id = db.EasyDB.select(test=1)
print(list(upy_id))

upy_id = db.EasyDB.scan()
print(list(upy_id))

db.db.close()

**Comment by pfalcon** [comment]
Thanks for your submission, micropython-btreedb's example is at
https://github.com/pfalcon/notes-pico .
